// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ContainerValidationBase.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

class CursorContainerValidation : public ContainerValidationBase {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CURSORCONTAINERVALIDATION
public:
    class CursorContainerValidation& operator=(class CursorContainerValidation const&) = delete;
    CursorContainerValidation(class CursorContainerValidation const&) = delete;
    CursorContainerValidation() = delete;
#endif

public:
    /*0*/ virtual ~CursorContainerValidation();
<<<<<<< HEAD
    /*1*/ virtual bool isValidSlotForContainer(class ContainerScreenContext const&, class Container const&, int) const;
    /*2*/ virtual void __unk_vfn_0();
    /*3*/ virtual void __unk_vfn_1() const;
=======
    /*2*/ virtual void __unk_vfn_2();
    /*4*/ virtual void __unk_vfn_4();
    /*5*/ virtual void __unk_vfn_5();
    /*6*/ virtual void __unk_vfn_6();
>>>>>>> 51d0529ff191cb743d7dd9047e8ce5e7edba226d
    /*
    inline int getContainerOffset(class ContainerScreenContext const& a0) const{
        int (CursorContainerValidation::*rv)(class ContainerScreenContext const&) const;
        *((void**)&rv) = dlsym("?getContainerOffset@CursorContainerValidation@@UEBAHAEBVContainerScreenContext@@@Z");
        return (this->*rv)(std::forward<class ContainerScreenContext const&>(a0));
    }
    inline bool canItemMoveToContainer(class ItemStackBase const& a0) const{
        bool (CursorContainerValidation::*rv)(class ItemStackBase const&) const;
        *((void**)&rv) = dlsym("?canItemMoveToContainer@CursorContainerValidation@@UEBA_NAEBVItemStackBase@@@Z");
        return (this->*rv)(std::forward<class ItemStackBase const&>(a0));
    }
    */

protected:

private:

};