// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "BlockActor.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

class DaylightDetectorBlockActor : public BlockActor {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_DAYLIGHTDETECTORBLOCKACTOR
public:
    class DaylightDetectorBlockActor& operator=(class DaylightDetectorBlockActor const&) = delete;
    DaylightDetectorBlockActor(class DaylightDetectorBlockActor const&) = delete;
    DaylightDetectorBlockActor() = delete;
#endif

public:
    /*0*/ virtual ~DaylightDetectorBlockActor();
<<<<<<< HEAD
    /*1*/ virtual void saveBlockData(class CompoundTag&, class BlockSource&) const;
    /*2*/ virtual void loadBlockData(class CompoundTag const&, class BlockSource&, class DataLoadHelper&);
    /*3*/ virtual void onCustomTagLoadDone(class BlockSource&);
    /*4*/ virtual void tick(class BlockSource&);
    /*5*/ virtual void onChanged(class BlockSource&);
    /*6*/ virtual void onPlace(class BlockSource&);
    /*7*/ virtual void __unk_vfn_0();
    /*8*/ virtual void onRemoved(class BlockSource&);
    /*9*/ virtual void triggerEvent(int, int);
    /*10*/ virtual void clearCache();
    /*11*/ virtual void __unk_vfn_1();
    /*12*/ virtual float getShadowRadius(class BlockSource&) const;
    /*13*/ virtual bool hasAlphaLayer() const;
    /*14*/ virtual void __unk_vfn_2();
    /*15*/ virtual std::string const& getCustomName() const;
    /*16*/ virtual std::string getName() const;
    /*17*/ virtual std::string getImmersiveReaderText(class BlockSource&);
    /*18*/ virtual int getRepairCost() const;
    /*19*/ virtual class PistonBlockActor* getOwningPiston(class BlockSource&);
    /*20*/ virtual void __unk_vfn_3();
    /*21*/ virtual void __unk_vfn_4();
    /*22*/ virtual float getDeletionDelayTimeSeconds() const;
    /*23*/ virtual void __unk_vfn_5();
    /*24*/ virtual void __unk_vfn_6();
    /*25*/ virtual void __unk_vfn_7();
    /*26*/ virtual std::unique_ptr<class BlockActorDataPacket> _getUpdatePacket(class BlockSource&);
    /*27*/ virtual void _onUpdatePacket(class CompoundTag const&, class BlockSource&);
    /*28*/ virtual bool _playerCanUpdate(class Player const&) const;
=======
    /*4*/ virtual void saveBlockData(class CompoundTag&, class BlockSource&) const;
    /*5*/ virtual void loadBlockData(class CompoundTag const&, class BlockSource&, class DataLoadHelper&);
    /*6*/ virtual void onCustomTagLoadDone(class BlockSource&);
    /*7*/ virtual void tick(class BlockSource&);
    /*8*/ virtual void onChanged(class BlockSource&);
    /*11*/ virtual void onPlace(class BlockSource&);
    /*12*/ virtual void __unk_vfn_12();
    /*13*/ virtual void onRemoved(class BlockSource&);
    /*14*/ virtual void triggerEvent(int, int);
    /*15*/ virtual void clearCache();
    /*16*/ virtual void __unk_vfn_16();
    /*17*/ virtual float getShadowRadius(class BlockSource&) const;
    /*18*/ virtual void __unk_vfn_18();
    /*19*/ virtual void __unk_vfn_19();
    /*21*/ virtual std::string const& getCustomName() const;
    /*23*/ virtual std::string getName() const;
    /*25*/ virtual std::string getImmersiveReaderText(class BlockSource&);
    /*26*/ virtual int getRepairCost() const;
    /*27*/ virtual class PistonBlockActor* getOwningPiston(class BlockSource&);
    /*28*/ virtual void __unk_vfn_28();
    /*29*/ virtual void __unk_vfn_29();
    /*30*/ virtual float getDeletionDelayTimeSeconds() const;
    /*31*/ virtual void __unk_vfn_31();
    /*32*/ virtual void __unk_vfn_32();
    /*33*/ virtual void __unk_vfn_33();
    /*34*/ virtual std::unique_ptr<class BlockActorDataPacket> _getUpdatePacket(class BlockSource&);
    /*35*/ virtual void _onUpdatePacket(class CompoundTag const&, class BlockSource&);
    /*36*/ virtual void __unk_vfn_36();
>>>>>>> 51d0529ff191cb743d7dd9047e8ce5e7edba226d

protected:

private:

};