// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

class EventResponse {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_EVENTRESPONSE
public:
    class EventResponse& operator=(class EventResponse const&) = delete;
    EventResponse(class EventResponse const&) = delete;
    EventResponse() = delete;
#endif

public:
    /*0*/ virtual ~EventResponse();
    /*1*/ virtual std::string const& getName() const;
<<<<<<< HEAD
    /*2*/ virtual void __unk_vfn_0() = 0;
=======
    /*2*/ virtual void __unk_vfn_2() = 0;
>>>>>>> 51d0529ff191cb743d7dd9047e8ce5e7edba226d
    /*3*/ virtual ~EventResponse();
    /*
    inline  ~EventResponse(){
         (EventResponse::*rv)();
        *((void**)&rv) = dlsym("??1EventResponse@@UEAA@XZ");
        return (this->*rv)();
    }
    */

protected:

private:

};