// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ContainerValidationBase.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

class FurnaceIngredientContainerValidation : public ContainerValidationBase {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_FURNACEINGREDIENTCONTAINERVALIDATION
public:
    class FurnaceIngredientContainerValidation& operator=(class FurnaceIngredientContainerValidation const&) = delete;
    FurnaceIngredientContainerValidation(class FurnaceIngredientContainerValidation const&) = delete;
    FurnaceIngredientContainerValidation() = delete;
#endif

public:
    /*0*/ virtual ~FurnaceIngredientContainerValidation();
<<<<<<< HEAD
    /*1*/ virtual bool isValidSlotForContainer(class ContainerScreenContext const&, class Container const&, int) const;
    /*2*/ virtual void __unk_vfn_0();
    /*3*/ virtual void __unk_vfn_1();
    /*4*/ virtual void __unk_vfn_2();
    /*5*/ virtual void __unk_vfn_3() const;
=======
    /*2*/ virtual void __unk_vfn_2();
    /*4*/ virtual void __unk_vfn_4();
    /*5*/ virtual void __unk_vfn_5();
    /*
    inline int getContainerOffset(class ContainerScreenContext const& a0) const{
        int (FurnaceIngredientContainerValidation::*rv)(class ContainerScreenContext const&) const;
        *((void**)&rv) = dlsym("?getContainerOffset@FurnaceIngredientContainerValidation@@UEBAHAEBVContainerScreenContext@@@Z");
        return (this->*rv)(std::forward<class ContainerScreenContext const&>(a0));
    }
    */
>>>>>>> 51d0529ff191cb743d7dd9047e8ce5e7edba226d

protected:

private:

};