// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

struct VolumeIdentifier {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_VOLUMEIDENTIFIER
public:
    struct VolumeIdentifier& operator=(struct VolumeIdentifier const&) = delete;
    VolumeIdentifier(struct VolumeIdentifier const&) = delete;
    VolumeIdentifier() = delete;
#endif

public:
<<<<<<< HEAD
    MCAPI struct VolumeIdentifier& operator=(struct VolumeIdentifier const&);
    MCAPI bool operator==(struct VolumeIdentifier const&) const;
=======
>>>>>>> 51d0529ff191cb743d7dd9047e8ce5e7edba226d

protected:

private:

};