#pragma once
#include <I18nAPI.h>

static const I18nBase::LangData defaultLangData = {
	{"en_US", {
		 {"tp.fail.rate", "Tpa speed too fast"},
		 {"tp.fail.inreq", "A tpa request is in progress"},
		 {"tp.fail.blocked", "The target player blocked the Tpa request"},
		 {"tp.name.required", "Need to specify target"},
		 {"home.is.full", "Reached the upper limit of Home!"},
		 {"home.not.found", "Can not find the warp"},
		 {"home.gui.title", "Home"},
		 {"home.gui.content", "Choose a home"},
		 {"warp.gui.title", "Warp System"},
		 {"warp.gui.content", "Choose a warp point"},
		 {"tpa.req.A_B", " would like to teleport to your position. Use \"/tpa ac\" to accept or use \"/tpa de\" to deny"},
		 {"tpa.req.B_A", " would like you to teleport to their position. Use \"/tpa ac\" to accept or use \"/tpa de\" to deny"},
		 {"tpa.reason.deny", "Teleport request denied."},
		 {"tpa.reason.timeout", "Teleport request timed out."},
		 {"tpa.reason.accept","Teleport request accepted."},
		 {"tpa.reason.notonline", "Target player not online"},
		 {"tpa.reason.cancel", "Teleport request cancelled."},
		 {"tpa.back.use", "Use /back to return to your death point."},
		 {"tpa.request.title", "Tpa request"},
		 {"tpa.request.accept", "Accept"},
		 {"tpa.request.deny", "Deny"},
		 {"tpa.gui.title", "Tpa Menu"},
		 {"tpa.gui.label", "Choose a player"},
		 {"tpa.gui.dropdown1", "Mode"},
		 {"tpa.gui.dropdown2", "Players"},
	}},
	{"zh_CN", {
		 {"tp.fail.rate", u8"TPA速度过快！！"},
		 {"tp.fail.inreq", u8"一个TPA正在进行"},
		 {"tp.fail.blocked", u8"对方屏蔽了TPA请求"},
		 {"tp.name.required", u8"需要指定目标"},
		 {"home.is.full", u8"达到Home设置上限！"},
		 {"home.not.found", u8"找不到传送点！"},
		 {"home.gui.title", u8"家"},
		 {"home.gui.content", u8"选择一个家"},
		 {"warp.gui.title", u8"传送点"},
		 {"warp.gui.content", u8"选择一个传送点"},
		 {"tpa.req.A_B", u8" 发起了一个传送到你的请求,使用/tpa ac接受,/tpa de拒绝"},
		 {"tpa.req.B_A",  u8"发起了一个传送到他的请求,使用 / tpa ac接受, / tpa de拒绝"},
		 {"tpa.reason.deny", u8"Tpa请求被拒绝"},
		 {"tpa.reason.timeout", u8"Tpa请求因超时自动取消"},
		 {"tpa.reason.accept",u8"Tpa请求已经被接受"},
		 {"tpa.reason.notonline", u8"目标玩家不在线"},
		 {"tpa.reason.cancel", u8"Tpa请求已取消"},
		 {"tpa.back.use",u8"可以使用/back返回上一个死亡点！"},
		 {"tpa.request.title", u8"Tpa请求"},
		 {"tpa.request.accept", u8"接受"},
		 {"tpa.request.deny", u8"拒绝"},
		 {"tpa.gui.title", u8"Tpa菜单"},
		 {"tpa.gui.label", u8"选择一个玩家"},
		 {"tpa.gui.dropdown1", u8"模式"},
		 {"tpa.gui.dropdown2", u8"玩家"},
	}}
};
